// <auto-generated />
namespace NotDefteri_DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class notebooktest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(notebooktest));
        
        string IMigrationMetadata.Id
        {
            get { return "202303051301203_notebooktest"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
